---
- name: Load Vars file
  include_vars:
    ansible.builtin.file: homeassistant.yml

- name: Run main.yml task to deploy docker container
  include_tasks:
    ansible.builtin.file: main.yml

- name: Ensure Directory is present for config files
  ansible.builtin.file:
    path: "{{ config_dir }}/{{ dc_container }}/{{ homeassistant_service }}/"
    state: directory
    mode: 0755
