---

- name: Find Sonoff Zigbee USB Stick
  ansible.builtin.find:
    paths: "/dev/serial/by-id/"
    contains: "usb-ITead_Sonoff_Zigbee*"
    use_regex: true
    file_type: link
  register: usb_sonoff_serial


- name: Load Vars file
  ansible.builtin.include_vars:
    file: zigbee2mqtt.yml

- name: Run main.yml task to deploy docker container
  ansible.builtin.include_tasks:
    file: main.yml

- name: Copy Zigbee2mqtt configuration to host.
  ansible.builtin.template:
    src: "zb2mqtt_configuration.yaml.j2"
    dest: "{{ config_dir }}/{{ dc_container }}/{{ zb2mqtt_service }}/configuration.yaml"
    mode: '0640'
  notify: restart container


- name: Copy Mosquitto configuration to host.
  ansible.builtin.template:
    src: "mosquitto.conf.j2"
    dest: "{{ config_dir }}/{{ dc_container }}/{{ mqtt_service }}/config/mosquitto.conf"
    mode: '0640'
  notify: restart container
